# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9ac4975191356b6ca7cd14a069b667398708c1623681299b64ab20aefd5dd119470aee512be02548f3e1ea150edc88149d879d2cc47fe80a827cd2668612c46

test:
  secret_key_base: 25ee651d3b14d31fcd5eb2a538b4e304677d0fd06c090715c60a4236add443cdc0e24bdbcda621348b657bfec5c42a2546c4ac6607cc26f0cc60774810619c9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
